import { Turnstile } from '@marsidev/react-turnstile'

import './App.css'
import axios from 'axios'
import { useState } from 'react'

function App() {
  const [token, setToken] = useState<string>("")

  return (
    <>
      <input placeholder='OTP'></input>
      <input placeholder='New password'></input>

      <Turnstile onSuccess={(token) => {   ///this will create the token when you click on i am not robot
        setToken(token)
      }} siteKey='0x4AAAAAAAgcCpTl5snUBP-Q' /> {/*this is generated by the cloudflare */}

      <button onClick={async() => {
        const res=await axios.post("http://localhost:3000/reset-password", {
          email: "j@gmail.com",
          otp: "123456",
          token: token,
        })
        console.log(res)
      }}>Update password</button>
    </>
  )
}

export default App